name: Build and Release DLL

on:
  push:
    branches:
      - master

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up MinGW
        uses: msys2/setup-msys2@v3
        with:
          update: true
          install: >
            mingw-w64-i686-gcc
            mingw-w64-i686-gcc-c++
            mingw-w64-i686-headers
            mingw-w64-i686-crt
            mingw-w64-i686-winpthreads

      - name: Build DLL
        run: |
          make clean
          make

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: out/d3d9.dll
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
